/** Narrative copy for the dedicated About page (source: site owner). */
export const aboutParagraphs: string[] = [
  "I grew up in Thalikulam, in a calm environment where there was no constant pressure to compete in the typical academic rat race. I never prepared for exams like JEE, and I never intended to. That path always felt predefined with a predictable outcome. Early on, I made a clear decision that still drives everything I do today. I do not want a normal life, and I am willing to accept the tradeoffs that come with that.",
  "Up until 10th grade, I was a strong academic student. Structured, consistent, and performing well within the system. That changed in 11th grade when I moved into a different environment and got deeper exposure to the internet, YouTube, and global communities. That shift changed what I paid attention to. For the first time, I could see people building things that were not tied to geography, degrees, or traditional career paths.",
  "I was always drawn to building. Not casually, but with a specific kind of curiosity. Drawing, design, structures, architecture, and systems. The common thread was scale. I was never interested in small isolated outputs. The focus was always on creating something that could extend beyond a single person and operate at a global level.",
  "Like most people starting without direction, I tried a lot of things and most of them failed. I spent time editing videos and still do, but I quickly understood that I did not want to build a career around it. Then came YouTube. I created five separate channels, each with a different direction, and all of them failed completely. No traction, no meaningful growth, no signal. That phase forced a realization that shaped how I work now. Effort alone does not matter. If the direction is wrong, you can execute perfectly and still end up nowhere.",
  "Over time, my focus shifted from trying random things to building systems that could scale. I became deeply interested in technology as leverage, especially AI. Tools like Claude, Cursor, and OpenAI Codex are not just tools I use occasionally. They are embedded into how I build and think. I am convinced that AI driven development is becoming the baseline, not an advantage.",
  "When it came to university, I had the option to take a more traditional and secure route, including paths like Australian National University. That would have been the safe decision with a clear structure and a predictable outcome. I chose not to take it. Instead, I moved to Dubai and joined University of Birmingham Dubai to study Robotics and AI. The decision was not about prestige. It was about control over time. I needed an environment that allowed me to build in parallel, not one that would consume all available bandwidth.",
  "That decision immediately translated into action. Within the first semester, I started building seriously. I participated in hackathons and placed third in one, but more importantly, I began working on products with real complexity and real users. University became secondary infrastructure. The main work happens outside it.",
  "At 18, I incorporated a company in the United States under the name Edge Platforms, Inc.. That was not a symbolic step. It was a commitment to operating at a level where things are built to work in the real world, not just as ideas or experiments.",
  "Right now, my life is not balanced in any conventional sense. Most days are built around 14 to 16 hours in front of a screen. Building, debugging, rewriting systems, and talking to users. There have been phases where more than 700 direct messages were sent within a single week as part of outbound efforts. The response rate was strong and more importantly, it validated something critical. There is real demand for what I am building. People are not just curious. They are waiting for it to work reliably.",
  "That validation comes with pressure. It removes the possibility of hiding behind uncertainty. The problem is no longer whether the idea matters. The problem is execution. The product has a large surface area, and making it reliable is significantly harder than generating interest. Every improvement exposes another layer that needs to be fixed. It is not clean or linear. It is iterative, messy, and constant.",
  "I am naturally introverted. That used to be something I could ignore. It is no longer possible. What I am building now requires direct communication, outreach, and sales. That shift is uncomfortable, but necessary. Avoiding it would slow everything down, and that is not acceptable.",
  "What I am focused on is not building short term tools or chasing trends. The goal is to build infrastructure. Systems that other people can rely on. Something that enables execution, not just ideas. Something that operates at scale and holds up under real usage.",
  "There are no inflated claims here. This is still early. The systems are still being refined. The product is still being pushed toward reliability. But the direction is clear, and the work is being done with full intensity.",
  "The immediate target is simple and measurable. Build something people consistently use, push it to real revenue, and scale from there. A concrete milestone I am working toward is reaching 100k in GMV before the end of 2026.",
  "I do not approach this passively. Things are built quickly, tested under pressure, broken, and rebuilt. A complex product with real infrastructure was taken from nothing to a working state within months. Not stable all the time, not polished, but real. That is the standard.",
  "This is not a side project. Not an experiment. Not something being done for experience."
];

export const aboutClosingLine = "This is being built to work.";
